name: owwn_coding_challenge
description: OWWN Coding Challenge.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=3.0.2"

dependencies:
  cupertino_icons: ^1.0.5
  flutter_secure_storage: ^6.0.0
  fluttertoast: ^8.0.9
  go_router: 5.0.0
  http: ^0.13.4
  http_interceptor: ^1.0.2
  provider: ^6.0.0
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2


flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 700
    - family: DMSerifDisplay
      fonts:
        - asset: assets/fonts/DMSerifDisplay-Regular.ttf
